import { describe, it, expect } from "vitest";
import { existsSync, statSync } from "node:fs";
import { join } from "node:path";
import { OnnxMLService } from "./OnnxMLService.js";
import { thumbBytes } from "./thumbSource.js";
import { quantize, dot } from "./quantize.js";
import { modelById, MODELS } from "./models.js";
import { NodeProcessingService } from "../processing/NodeProcessingService.js";

/**
 * DOES THE PIPELINE PRODUCE MEANINGFUL VECTORS, OR MERELY WELL-FORMED ONES?
 *
 * Every other test in this feature checks SHAPE: the tensor is rank 2, the
 * dimension matches the registry, the values are finite, the norm is 1, the
 * int8 dot product tracks float cosine. A pipeline with a subtly wrong
 * preprocessing step — swapped colour channels, the wrong normalization
 * constants, the wrong resize filter — passes every single one of those and
 * still produces vectors that cluster like noise. Nothing downstream could
 * detect it: #162 (near-duplicates), #163 (clusters), #164 (tags) and #165
 * (the scatter) would each be confidently, silently wrong, and the first
 * symptom would be a user saying "these don't look like duplicates to me".
 *
 * So this is the one test that asks whether the numbers MEAN anything. Two
 * near-consecutive frames of the same scene must land close together, and a
 * photograph of something else must land far away. That is the whole
 * behavioural contract the four consumer issues rest on.
 *
 * It also covers batch attribution for free: `embedImages` returns one vector
 * per input and the sweep stores them by index, so if the batch->row mapping
 * were ever off by one or transposed, the "similar" pair would stop being the
 * close pair and this test would fail. A shape assertion cannot see that.
 *
 * WHY IT IS GATED. It needs a real model (~89-94 MB) and real inference, and
 * the suite's standing rule is that `npm test` never downloads a model or
 * spawns a child. It also needs photographs, and this repository is public:
 * every image fixture in the tree is generated by sharp at test time
 * (`e2e/fixture.mjs`), and the only committed image is `ui/public/icon.png`.
 * Real photographs of identifiable people do not belong in a public repo, so
 * the fixtures stay on the developer's disk and the path is supplied by an
 * environment variable, in the same spirit as the gitignored
 * `docs/TEST_FOLDERS.local.md`.
 *
 * TO RUN IT:
 *   AUTOGALLERY_EMBED_FIXTURES=/path/to/folder ML_INTEGRATION=1 \
 *     npx vitest run server/ml/embeddingSimilarity.test.js
 *
 * The folder needs three photographs: two that are near-duplicates of each
 * other (consecutive frames of one scene — a burst is ideal) and one of a
 * clearly different subject. Name them so the intent survives the next reader:
 * `*_similar.JPG` x2 and `*_different.JPG` x1.
 */

const FIXTURE_DIR = process.env.AUTOGALLERY_EMBED_FIXTURES;

/** The two near-duplicates, then the odd one out. Order is load-bearing: the
 *  assertions below index into this array. */
const FIXTURES = [
  "3S2A9874_similar.JPG",
  "3S2A9875_similar.JPG",
  "3S2A9974_different.JPG",
];

const haveFixtures =
  Boolean(FIXTURE_DIR) &&
  FIXTURES.every((f) => existsSync(join(FIXTURE_DIR, f)));

/**
 * MEASURED 2026-07-26 on darwin/arm64, so a future reader can tell genuine
 * drift from an outright break rather than guessing at the thresholds:
 *
 *   model                          similar   vs different   dim
 *   Xenova/clip-vit-base-patch32    0.9747   0.528 / 0.547  512
 *   Xenova/siglip-base-patch16-224  0.9793   0.585 / 0.597  768
 *
 * The thresholds below sit far outside that spread deliberately. They are not
 * trying to pin the exact numbers — those move with the model, the dtype and
 * the JPEG encoder — they are trying to catch the case where the ordering
 * collapses. A pipeline that scores a near-duplicate at 0.62 and an unrelated
 * photo at 0.58 is broken even though both numbers look plausible in
 * isolation, which is exactly why the GAP is asserted and not just the
 * absolute values.
 */
const SIMILAR_FLOOR = 0.9;
const DIFFERENT_CEILING = 0.8;
const MIN_GAP = 0.25;

const integration =
  process.env.ML_INTEGRATION === "1" && haveFixtures ? describe : describe.skip;

if (process.env.ML_INTEGRATION === "1" && !haveFixtures) {
  // Loud, not silent. A gated test that quietly does nothing when its fixtures
  // are missing is indistinguishable from a passing one, and this is the only
  // check that the vectors mean anything.
  console.warn(
    `[embeddingSimilarity] SKIPPED: set AUTOGALLERY_EMBED_FIXTURES to a folder containing ${FIXTURES.join(", ")}`
  );
}

/** Cosine similarity through the REAL storage path — quantize to int8 exactly
 *  as `embedAllPending` does, then compare the way a consumer will. Comparing
 *  the raw float32 vectors instead would test a code path nothing uses and
 *  would hide any similarity the quantization itself destroys. */
function cosine(a, b) {
  return dot(a.bytes, b.bytes) * a.scale * b.scale;
}

integration("embeddings are semantically meaningful", () => {
  for (const spec of MODELS) {
    it(`${spec.label}: near-duplicates cluster, a different scene does not`, async () => {
      const processing = new NodeProcessingService();
      const ml = new OnnxMLService();
      try {
        await ml.configure({ modelId: spec.id, threads: 4 });

        // Through thumbSource, not sharp directly: the 320px thumbnail IS
        // what the sweep feeds the encoder, so testing anything else would
        // verify a pipeline that never runs in production.
        const buffers = [];
        for (const name of FIXTURES) {
          const path = join(FIXTURE_DIR, name);
          const st = statSync(path);
          buffers.push(
            await thumbBytes(
              {
                path,
                mtime: Math.floor(st.mtimeMs),
                size: st.size,
                kind: "image",
              },
              processing
            )
          );
        }

        const vectors = await ml.embedImages(buffers);
        expect(vectors).toHaveLength(FIXTURES.length);
        for (const v of vectors) {
          expect(v).toHaveLength(modelById(spec.id).dim);
        }

        const [a, b, other] = vectors.map(quantize);
        const alike = cosine(a, b);
        const unlikeA = cosine(a, other);
        const unlikeB = cosine(b, other);

        // Reported unconditionally: when this test fails, the three numbers
        // are the entire diagnosis, and a bare "expected true to be false"
        // would send the next person back here to re-instrument it.
        console.log(
          `[${spec.id}] similar=${alike.toFixed(4)} ` +
            `different=${unlikeA.toFixed(4)}/${unlikeB.toFixed(4)}`
        );

        expect(alike).toBeGreaterThan(SIMILAR_FLOOR);
        expect(unlikeA).toBeLessThan(DIFFERENT_CEILING);
        expect(unlikeB).toBeLessThan(DIFFERENT_CEILING);

        // The load-bearing one. Absolute thresholds can both drift with a
        // model change while the ordering stays correct; if this gap ever
        // closes, similarity has stopped meaning anything regardless of
        // where the individual numbers landed.
        expect(alike - Math.max(unlikeA, unlikeB)).toBeGreaterThan(MIN_GAP);
      } finally {
        ml.stop();
      }
    }, 600_000);
  }
});
