import { describe, it, expect } from "vitest";
import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { OnnxMLService } from "./OnnxMLService.js";
import { thumbBytes } from "./thumbSource.js";
import { quantize, dot } from "./quantize.js";
import { modelById, MODELS } from "./models.js";
import { NodeProcessingService } from "../processing/NodeProcessingService.js";

/**
 * DOES THE PIPELINE PRODUCE MEANINGFUL VECTORS, OR MERELY WELL-FORMED ONES?
 *
 * Every other test in this feature checks SHAPE: the tensor is rank 2, the
 * dimension matches the registry, the values are finite, the norm is 1, the
 * int8 dot product tracks float cosine. A pipeline with a subtly wrong
 * preprocessing step — swapped colour channels, the wrong normalization
 * constants, the wrong resize filter — passes every single one of those and
 * still produces vectors that cluster like noise. Nothing downstream could
 * detect it: #162 (near-duplicates), #163 (clusters), #164 (tags) and #165
 * (the scatter) would each be confidently, silently wrong, and the first
 * symptom would be a user saying "these don't look like duplicates to me".
 *
 * So this is the one test that asks whether the numbers MEAN anything.
 *
 * IT EMBEDS THE THUMBNAIL, NOT THE ORIGINAL. `thumbBytes` is the same function
 * `embedAllPending` calls, so the bytes reaching the encoder here are the same
 * 320px JPEG the sweep produces. Handing sharp the full-size file instead would
 * verify a pipeline that never runs in production.
 *
 * IT ALSO COVERS BATCH ATTRIBUTION FOR FREE. `embedImages` returns one vector
 * per input and the sweep stores them by index, so an off-by-one or transposed
 * batch mapping would stop the near-duplicates being the close pair. That
 * failure would give every photo in a 114k library someone else's vector, and
 * no shape assertion can see it. (Verified: scrambling the result order makes
 * this test fail.)
 *
 * WHY IT IS GATED TWICE, both deliberately. It needs a real model (~89-94 MB)
 * and real inference, and the suite's standing rule is that `npm test` never
 * downloads a model or spawns a child. It also needs photographs, and this
 * repository is public: every image fixture in the tree is generated by sharp
 * at test time (`e2e/fixture.mjs`), and the only committed image is
 * `ui/public/icon.png`. Real photographs stay on the developer's disk and the
 * path arrives by environment variable, in the same spirit as the gitignored
 * `docs/TEST_FOLDERS.local.md`.
 *
 * TO RUN IT:
 *   AUTOGALLERY_EMBED_FIXTURES=/path/to/folder ML_INTEGRATION=1 \
 *     npx vitest run server/ml/embeddingSimilarity.test.js
 *
 * The folder needs five photographs, named by role (the suffix IS the
 * contract — see discoverFixtures):
 *   *_burst.*     x2  two frames of one burst — the tightest duplicate
 *   *_similar.*   x2  one scene re-framed from a different position
 *   *_different.* x1  a clearly unrelated subject
 */

const FIXTURE_DIR = process.env.AUTOGALLERY_EMBED_FIXTURES;

/**
 * Discovered by NAMING CONVENTION, never by hard-coded filenames.
 *
 * The first revision listed three exact filenames. Swapping the photographs
 * for a different set — which is a thing anyone reasonably does, e.g. to
 * replace pictures of people with pictures of a sandwich — silently turned the
 * whole check off, because a missing file reads as "no fixtures configured"
 * and skips. A test that disappears when its inputs change is worse than no
 * test, so the role suffix is what the code reads.
 *
 * @param {string|undefined} dir
 * @returns {{roles: {burst: string[], similar: string[], different: string}|null, why: string}}
 */
function discoverFixtures(dir) {
  if (!dir)
    return { roles: null, why: "AUTOGALLERY_EMBED_FIXTURES is not set" };
  if (!existsSync(dir)) return { roles: null, why: `${dir} does not exist` };

  const images = readdirSync(dir).filter((f) => /\.(jpe?g|png|webp)$/i.test(f));
  const byRole = (role) =>
    images.filter((f) => new RegExp(`_${role}\\.[^.]+$`, "i").test(f)).sort();

  const burst = byRole("burst");
  const similar = byRole("similar");
  const different = byRole("different");

  if (burst.length < 2 || similar.length < 2 || different.length < 1) {
    return {
      roles: null,
      why:
        `${dir} needs two *_burst.*, two *_similar.* and one *_different.* ` +
        `image (found ${burst.length}/${similar.length}/${different.length})`,
    };
  }
  return {
    roles: {
      burst: [burst[0], burst[1]],
      similar: [similar[0], similar[1]],
      different: different[0],
    },
    why: "",
  };
}

const { roles: FIXTURES, why: fixtureProblem } = discoverFixtures(FIXTURE_DIR);

/**
 * MEASURED 2026-07-26, darwin/arm64, both shipping models. Recorded so a future
 * reader can tell genuine drift from an outright break instead of guessing:
 *
 *   relation                                   SigLIP    CLIP
 *   burst pair (same moment)                   0.9608   0.9657
 *   similar pair (one scene, re-framed)        0.9326   0.8854
 *   two DIFFERENT outdoor scenes               0.6071   0.6771
 *   outdoor scene vs an indoor close-up        0.50-0.56  0.41-0.52
 *
 * THREE THINGS THAT ORDERING TEACHES, all of which shape the assertions:
 *
 * 1. "Near-duplicate" is not one number. A burst scores ~0.96; the same scene
 *    re-framed scores 0.89-0.93. An earlier revision set a single 0.90 floor,
 *    calibrated on bursts, and the re-framed pair then failed at 0.8707 on CLIP
 *    — despite being exactly what #162 must catch. Hence two floors.
 *
 * 2. Unrelated is not one number either. Two different street scenes sit at
 *    0.61-0.68 — well above street-vs-sandwich at 0.41-0.56 — because they
 *    genuinely share subject matter. That is the model being right, not wrong,
 *    and it is why the gap below is measured against the UNRELATED SUBJECT and
 *    the cross-scene pair only has to stay under a ceiling.
 *
 * 3. The floors exist only to catch total collapse (everything landing in a
 *    noise band around 0.5), which a gap check alone could survive. Do NOT
 *    tighten them to hug whatever the current fixtures happen to score — that
 *    is how this test starts failing for the wrong reason again.
 */
const BURST_FLOOR = 0.9;
const SIMILAR_FLOOR = 0.75;
const UNRELATED_CEILING = 0.8;
const MIN_GAP = 0.25;

const integration =
  process.env.ML_INTEGRATION === "1" && FIXTURES ? describe : describe.skip;

if (process.env.ML_INTEGRATION === "1" && !FIXTURES) {
  // Loud, not silent. A gated test that quietly does nothing when its fixtures
  // are missing is indistinguishable from a passing one, and this is the only
  // check that the vectors mean anything at all.
  console.warn(`[embeddingSimilarity] SKIPPED — ${fixtureProblem}`);
}

/** Cosine through the REAL storage path: quantize to int8 exactly as
 *  `embedAllPending` does, then compare the way a consumer will. Comparing the
 *  raw float32 vectors would test a code path nothing uses, and would hide any
 *  similarity the quantization itself destroys. */
function cosine(a, b) {
  return dot(a.bytes, b.bytes) * a.scale * b.scale;
}

integration("embeddings are semantically meaningful", () => {
  for (const spec of MODELS) {
    it(`${spec.label}: burst > re-framed > unrelated, by a usable margin`, async () => {
      const processing = new NodeProcessingService();
      const ml = new OnnxMLService();
      try {
        await ml.configure({ modelId: spec.id, threads: 4 });

        const names = [
          ...FIXTURES.burst,
          ...FIXTURES.similar,
          FIXTURES.different,
        ];
        const buffers = [];
        for (const name of names) {
          const path = join(FIXTURE_DIR, name);
          const st = statSync(path);
          buffers.push(
            await thumbBytes(
              {
                path,
                mtime: Math.floor(st.mtimeMs),
                size: st.size,
                kind: "image",
              },
              processing
            )
          );
        }

        const vectors = await ml.embedImages(buffers);
        expect(vectors).toHaveLength(names.length);
        for (const v of vectors) {
          expect(v).toHaveLength(modelById(spec.id).dim);
        }

        const [burstA, burstB, simA, simB, other] = vectors.map(quantize);

        const burstPair = cosine(burstA, burstB);
        const similarPair = cosine(simA, simB);
        // Two unrelated photographs that merely share a genre (both outdoor
        // street scenes). Legitimately closer than a wholly different
        // subject, so it gets a ceiling rather than a place in the gap.
        const crossScene = cosine(burstA, simA);
        const vsOtherSubject = [
          cosine(burstA, other),
          cosine(burstB, other),
          cosine(simA, other),
          cosine(simB, other),
        ];

        // Printed unconditionally: on failure these numbers ARE the
        // diagnosis, and a bare "expected true to be false" would send the
        // next reader straight back here to re-instrument it.
        console.log(
          `[${spec.id}] burst=${burstPair.toFixed(4)} ` +
            `similar=${similarPair.toFixed(4)} ` +
            `cross-scene=${crossScene.toFixed(4)} ` +
            `vs-other=${vsOtherSubject.map((n) => n.toFixed(4)).join("/")}`
        );

        expect(burstPair).toBeGreaterThan(BURST_FLOOR);
        expect(similarPair).toBeGreaterThan(SIMILAR_FLOOR);
        expect(crossScene).toBeLessThan(UNRELATED_CEILING);
        for (const s of vsOtherSubject) {
          expect(s).toBeLessThan(UNRELATED_CEILING);
        }

        // THE LOAD-BEARING ONE. Every absolute threshold above can drift with
        // a model or dtype change while the ordering stays perfectly correct.
        // If this margin ever closes, similarity has stopped meaning anything
        // no matter how respectable the individual numbers look.
        const nearest = Math.min(burstPair, similarPair);
        expect(nearest - Math.max(...vsOtherSubject)).toBeGreaterThan(MIN_GAP);
      } finally {
        ml.stop();
      }
    }, 600_000);
  }
});
